#!/usr/bin/env sh

_() {
  YEAR="1999"

  echo "GitHub Username: "
  read -r USERNAME
  echo "GitHub Access Token: (input hidden)"
  stty -echo
  read -r ACCESS_TOKEN
  stty echo
  echo

  [ -z "$USERNAME" ] && echo "Username is required." && exit 1
  [ -z "$ACCESS_TOKEN" ] && echo "Access token is required." && exit 1  

  [ ! -d "$YEAR" ] && mkdir "$YEAR"
  cd "$YEAR" || exit

  git init

  echo "# ${YEAR}" > README.md
  echo "" >> README.md
  echo "A commit from the past." >> README.md
  echo "" >> README.md
  echo "---" >> README.md
  echo "" >> README.md
  echo "*Generated by [${YEAR}-sc](https://github.com/${USERNAME}/${YEAR}-sc)*" >> README.md

  git add .

  GIT_AUTHOR_DATE="${YEAR}-01-01T18:00:00" \
  GIT_COMMITTER_DATE="${YEAR}-01-01T18:00:00" \
  git commit -m "Hello from ${YEAR}. Time travel experiment initiated."

  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f

  cd ..
  rm -rf "$YEAR"

  echo
  echo "Complete."
  echo "View your contribution: https://github.com/${USERNAME}/${YEAR}"
} && _

unset -f _
